title: Igor Staszkiewicz Page
description: Short Description of reality and myself
baseurl: "/igorsta.hithub.io/" # Repository name (if project site)
url: "https://igorsta.github.io" # No trailing slash!

plugins:
  - jekyll-feed
